### ISSUE TITLE
User Feedback When Clicking Newsletter "Subscribe" Button

### ISSUE THREAD

**Issue by carlykiang** [Stoccoin-Official/Stoccoin-Website#317] opened 2023-06-22 10:33 UTC
**Description:**
Currently, when users submit their emails for the newsletter, there is no feedback provided to signal to the user that the form with their details was submitted after clicking the "Subscribe" button. It would be helpful to include a popup or redirect to a secondary page stating that subscription to the newsletter has been successful.  

**Issue Type:** UI/UX

**Details:**
<img width="400" alt="Newsletter" src="https://github.com/Stoccoin-Official/Stoccoin-Website/assets/86347313/a22a47df-4ae3-4810-b68b-e0e11c8eecd7">

**Comment by royalpinto007** [comment] 2023-06-22 10:41
Cool, please submit a PR incase you are willing to work on this issue, thanks!

**Comment by carlykiang** [comment] 2023-06-22 11:03
> Cool, please submit a PR incase you are willing to work on this issue, thanks!

Got it, working on it right now!

**Comment by ChavvaNarayana** [comment] 2023-06-22 13:16
Hey, @royalpinto007   I wanted to bring to your attention that though i have implemented feedback for the user When Clicking Newsletter "Subscribe" Button, it is not working as expected. When a user enters their email and clicks the "Subscribe" button, nothing happens. The form does not submit or trigger any action.


### Expected Behavior:

Upon clicking the "Subscribe" button, the form should submit, and the entered email should be processed for subscription.




It may be beneficial to create a separate issue to address this problem.

**Comment by royalpinto007** [comment] 2023-06-22 13:38
Hey @ChavvaNarayana, I appreciate your efforts in solving the issue. However, since this issue has already been assigned to @carlykiang, and in the open-source world, we don't like clashes to happen, I can't consider your pull request. 
Thanks for understanding!

**Comment by royalpinto007** [comment] 2023-06-24 02:42
Hi @carlykiang,
Have you completed the work?
Please provide an update. It seems like you have been assigned for quite a while. If not, we can go ahead with @ChavvaNarayana's PR.
Thanks!

**Comment by royalpinto007** [comment] 2023-06-25 09:13
Since we haven't received any response from @carlykiang, I am closing this issue with @ChavvaNarayana PR. 
Thanks!

**Closed** 2023-06-25 09:14 UTC
Labels: good first issue

**Comment by carlykiang** [comment] 2023-06-26 12:04
Apologies, didn't see this earlier, sounds good!
